### ISSUE TITLE
ts.Client undefined

### ISSUE THREAD

**Issue by tmwoods** [Henry-Sarabia/igdb#1]
Hey! I'm new to using this project and looks like it will be perfect if I can get it running.

When getting the project from github (and when trying to build my own project) I'm getting the following error:

> ../../../../../github.com/Henry-Sarabia/igdb/testing.go:44: ts.Client undefined (type *httptest.Server has no field or method Client)

I pulled the latest about an hour ago.

Thanks!

**Comment by Henry-Sarabia** [comment]
Ah right I forgot to mention that the package is using the [httptest.Server Client](https://golang.org/pkg/net/http/httptest/#Server.Client) from the Go 1.9 spec. I'll update the README to reflect that.

To fix your problem, I recommend updating to the latest version of Go. 

If you can't do that for whatever reason, you can fork the repo, navigate to line 44 in testing.go, and replace `ts.Client()` with `http.DefaultClient`. It should work just fine after that.

**Comment by tmwoods** [comment]
Yep, worked like a charm. I'm running an earlier version on Ubuntu so `http.DefaultClient` did the trick.

Thanks!
