### ISSUE TITLE
Offset and Limit options have erroneous hard limits

### ISSUE THREAD

**Issue by ksewo** [Henry-Sarabia/igdb#100]
SetLimit and SetOffset returns error if number higher than 5000 is provided.

There is no limit for offset for IGDB v4 API.
![image](https://user-images.githubusercontent.com/35114395/99301142-ce14e200-284d-11eb-94fe-591d97476ba7.png)

Limit also changed to 500 (not 5000 as in the code).
![image](https://user-images.githubusercontent.com/35114395/99301198-e422a280-284d-11eb-8869-c3255ac27a07.png)

According to:
https://api-docs.igdb.com/#pagination

**Comment by Henry-Sarabia** [comment]
Oh my, that's no good -- nice catch! I'll have this fixed up in the next patch. Thanks for contributing!
