### ISSUE TITLE
Private endpoints may need additional authorization

### ISSUE THREAD

**Issue by Henry-Sarabia** [Henry-Sarabia/igdb#36]
There may be an additional required header to be sent in each request for pro and enterprise tier users. If this is the case, the auth token must be supported in the NewClient function or another function entirely.

**Comment by Henry-Sarabia** [comment]
Because I don't have access to a Pro tier account, I can't check whether or not the private endpoints will work without the additional auth token. For now, I will be leaving the private endpoints as part of the package until I or another user can verify their behavior.

**Comment by rogersachan** [comment]
is this still an issue now that everyone has been bumped to pro?

**Comment by Henry-Sarabia** [comment]
You're right, it's no longer an issue. Thanks for the heads up!
