### ISSUE TITLE
IGDB v4 Support

### ISSUE THREAD

**Issue by Lavos** [Henry-Sarabia/igdb#69]
IGDB announced that they are making some impactful changes to their API in `v4`.

The changes are too extensive to be listed here, please see their documentation on migration:
https://api-docs.igdb.com/#upgrading-to-v4-from-v3

**Comment by Henry-Sarabia** [comment]
The changes look straightforward and are well-documented. Shouldn't take too long to get up-to-date.

Thanks for the heads up.
