### ISSUE TITLE
ServerError struct does not have Temporary method

### ISSUE THREAD

**Issue by Lavos** [Henry-Sarabia/igdb#97]
When attempting to assert that the `errors.Cause(err)` of a returned `error` from a service is `Temporary` for the new ratelimiting requirements:

```go
type temporary interface {
        Temporary() bool
}

func IsTemporary(err error) bool {
        te, ok := errors.Cause(err).(temporary)
        fmt.Printf("IS TEMPORARY %#v %t\n", errors.Cause(err), ok)
        return ok && te.Temporary()
}
```

This prints:
```
IS TEMPORARY igdb.ServerError{Status:429, Msg:"too many requests", Temp:true} false
```

`errors.Cause()` returns a plain `igdb.ServerError`, not `*igdb.ServerError`, and a plain `igdb.ServerError` does not implement `temporary`. Only `*igdb.ServerError` has the required `Temporary` method:
https://github.com/Henry-Sarabia/igdb/blob/dcac61d5a6ea36eb1265af5e5f0cfdf479adf14f/error.go#L72

Is there any reason we can't define this method on `igdb.ServerError` as that will cover both plain struct and pointer?

**Comment by Henry-Sarabia** [comment]
Looking at it now, there is no reason the method should be defined on the pointer.
Good looking out!

`Temporary` will be `igdb.ServerError`'s method in the next patch.

**Comment by Lavos** [comment]
Fantastic! Thanks for the update. 👍
